### ISSUE TITLE
Feedback from DOM?

### ISSUE THREAD

**Issue by fluffynukeit** [bodil/purescript-signal#22]
The Mario and Purescript is Magic examples both get all their input from the keyboard/mouse.  Most GUIs, however, have feedback from events on GUI elements like clicks on items, drags, drops, etc.  It would be really helpful to see an example of such a GUI implemented with purescript-signal, even if minimal. I'd like to see the canonical way to subscribe to such events and how to work with them.  

If it's possible, it's not clear to me how to do it.  I don't believe there is currently a general function to listen to DOM events and convert them into a `Signal`.

**Comment by fluffynukeit** [comment]
About the same time I mentioned this, `Channel` was added.  It looks like the natural way to do this will be to create a channel, set DOM event handlers to push to the channel in the view, and subscribe to those push events elsewhere.  Feel free to chime in if you think there is a more canonical way to handle this.

**Comment by bodil** [comment]
Oops, yes, this issue was actually what got me to get around to adding in the Channel code, which has been lying around my system for a while. I'd completely forgotten the issue even existed by the time I was ready to commit, however.

You might want to look at how Channels and Signals interact in Elm for a DOM use case. This implementation is slightly simpler, lacking Elm's event loop, but should be more or less equivalent in usage. I plan to extend purescript-smolder with support for this as well.

**Comment by fluffynukeit** [comment]
Awesome, thanks.

**Comment by bodil** [comment]
It's not a complete reimplementation at this point, I've just added functions as I've needed them. A few things are still missing.

**Comment by fluffynukeit** [comment]
I made an exploratory example game using signal and vdom, including channels.  [purescript-puzzler](https://github.com/fluffynukeit/purescript-puzzler/).

I found in making it that it would be really useful to have an effectful fold function `foldpE` (shown [here](https://github.com/fluffynukeit/purescript-puzzler/blob/master/src/View.purs#L46-L59)).  It wasn't clear to me how to get this functionality with the existing combinators, so I just made my own.

This was a challenging learning exercise for me.  I wrote about some of the challenges [on my blog](http://fluffynukeit.com/exploring-the-mvi-architecture-with-purescript-puzzler/), if you are interested.  If you give it a read, please let me know if I'm doing something dumb.  :)

Thanks again.

**Comment by bodil** [comment]
Idk, it looks reasonable enough to me at first glance, but an effectful foldp is still making me feel a bit uncomfortable. I'd try to do a pure `foldp` followed by a map to an effectful function instead, and passing it to `runSignal`, which is basically the same thing, and I couldn't really explain why I think that's any cleaner.

**Comment by paf31** [comment]
The way I handled this in `purescript-halogen` was to replace the top-level `Signal HTML` with a signal function `Signal input -> Signal (HTML input)`. Then, a function is provided which takes this signal function and ties the knot, passing the generated inputs back into the first signal, and runs the application. This way, you might be able to avoid `Channel` apart from at the top-level, effectively confining the impure code to the top-level.
