### ISSUE TITLE
More documentation for functions

### ISSUE THREAD

**Issue by alexchandel** [bodil/purescript-signal#26]
For example, what is the difference between `distinct` and `distinct'`? (I'm seriously asking, I just assumed I wanted `distinct'`).

Even for ones similar to Elm functions like `<~`, `~>`, and `~`, it'd be useful to note the equivalent native functions (`<$>`, `<#>`, and `<*>` respectively) in the doc comment of each.

**Comment by bodil** [comment]
I think I've documented every function now, so I'll risk closing this one.
