### ISSUE TITLE
fps and fpsWhen

### ISSUE THREAD

**Issue by vstastny** [bodil/purescript-signal#43]
I tried to use fps and fpsWhen time functions, which are in elm, but found out that they are missing  here. Is it on purpose? Could they be composed from other primitives? Or just to be yet included later on?

**Comment by bodil** [comment]
Signal definitely isn't in sync with Elm's `Time` package. I've made an effort to stay in sync with `Signal`, but nothing more. That's not to say these couldn't be added, though - if they're in Elm core, I generally don't mind including them. You can definitely build them from existing primitives already, though.

**Comment by vstastny** [comment]
Ok. Thanks.
