### ISSUE TITLE
Help with maintenance 

### ISSUE THREAD

**Issue by CarstenKoenig** [bodil/purescript-signal#64]
Hi, @bodil 

even though Elm went a different path I still enjoy this library for demos and my leisure time projects and I would very much like to help you out with maintaining it.

Right now there are two PRs that would really help me out (yeah one is from me: #63) and I would like to remove the Elm references (as they are no longer working) etc.

I'm sure you are busy else where and maybe you moved on but if you like I just get back to me and let me know if we could work this out.

Thank you for your great work and of course your time.

**Comment by bodil** [comment]
Well, someone should probably maintain it, and it's probably better if it's not me, or turnaround time wouldn't be that great. Maybe it should go in purescript-contrib if people are still actually using it a lot, but for now I'm OK with giving you commit access, if you want to take responsibility for making it 0.12 compliant etc.

**Comment by CarstenKoenig** [comment]
I'm fine with both options - I'm not sure who I should contact regarding purescript-contrib but if you prefer this I'll see what I can find out.

If you give me write access I'll would happily try to port this over to 0.12 - of course I can start doing this on my fork and give you a PR as well, if you want to wait and see if I do something acceptable ;)

**Comment by bodil** [comment]
Sounds like a plan - let's do a PR. 👍

**Comment by newlandsvalley** [comment]
I've had a crack at porting to 0.12 - https://github.com/newlandsvalley/purescript-signal/tree/compiler/0.12.  Sorry about the impatience - almost all my repos depend on it in some manner or other.

**Comment by CarstenKoenig** [comment]
@newlandsvalley cool thanks (don't think I would have done differently) - to be honest I was waiting because I was expecting that there are issues with other dependencies (all other libs I looked at in the last few days had)

maybe @bodil can give you or me write access to get the changes in - there are a couple of other PRs that would be cool to have as well.

**Comment by bodil** [comment]
Looks good to me. @newlandsvalley, can you make a PR of it?

**Comment by newlandsvalley** [comment]
Many thanks @bodil - will do.  @CarstenKoenig - would you be happy to merge your other changes __after__ I've submitted the PR?

**Comment by CarstenKoenig** [comment]
I'll be happy if anyone merges them at any time they find time ;)

**Comment by bodil** [comment]
OK, I've merged it, now who wants commit access to tag the release? 😊

**Comment by CarstenKoenig** [comment]
I guess @newlandsvalley earned the privilege but as I said in the beginning I would love to help you out

btw: thanks for merging and all your work for ps - don't know if you've seen this but apparently this lib is still in use for try-purescript so it's quite important

**Comment by bodil** [comment]
I'm asking who wants it, long term. Apparently there are users, so there's responsibility involved. 😊

**Comment by newlandsvalley** [comment]
I'm not entirely confident that I can continue to maintain this up to your high standards, @bodil - I'd be very happy if @CarstenKoenig took it over.

**Comment by CarstenKoenig** [comment]
I'll take it if you want - just let me know how you want to continue

I guess for now it's probably enough if you just give me or one of us the rights to merge etc.

again - thanks for your time and work - much appreciated

**Comment by bodil** [comment]
OK, @CarstenKoenig, you should have commit access now. Making releases is just a matter of making the appropriate git tag - `bower version` is my preferred way to do it.

I guess that means we can close this issue. 😊

**Comment by bodil** [comment]
Oh, and you should feel free to add features and tag releases as you like without checking with me first, just try not to break too much user code that depends on this library in the process. 😊

**Comment by CarstenKoenig** [comment]
Thanks - I will do my best

**Comment by newlandsvalley** [comment]
Just noticed that the version in `bower` is still at 8.0.0 and not 10.0.0.  I guess @bodil meant that she tends to prepare a new version first by updating the bower version and then by `git tag - bower version`.

**Comment by bodil** [comment]
`bower version` should bump the version in all the right places, but I notice the `bower.json` file still reads 8.0.0. The version field has been deprecated, iirc, I guess the client stopped bumping it. The right thing to do is probably to take the version field out of the file.

**Comment by CarstenKoenig** [comment]
oh ok - sorry - I actually misinterpreted how `bower` works - for now I bumped the version (do I have to retag the commit? The documentation I found of it is a bit lacking)

**Comment by bodil** [comment]
Tbh, I have no idea, Bower is confusing, especially lately.

**Comment by CarstenKoenig** [comment]
yeah - turned out you could not just bump it - bower will see the release and complaint about different version

so the only thing I could think of, was make a new release - **really sorry** for that mess :(

but now it should be fine:

    bower purescript-signal#*   not-cached https://github.com/bodil/purescript-signal.git#*
    bower purescript-signal#*      resolve https://github.com/bodil/purescript-signal.git#*
   bower purescript-signal#*     download https://github.com/bodil/purescript-signal/archive/v10.1.0.tar.gz
   bower purescript-signal#*      extract archive.tar.gz
   bower purescript-signal#*     resolved https://github.com/bodil/purescript-signal.git#10.1.0

**Comment by CarstenKoenig** [comment]
Pursuit should be updated too - I guess I should really take care and have a look the next time I do this - I'll try and find out if the version field is needed and if `pulp version` will deal with it (I thought it should/would)

thanks for letting me know
